### ISSUE TITLE
Weird results

### ISSUE THREAD

**Issue by Nakilon** [raypereda/stemmify#4]
```
$ ruby -rstemmify -e "p 'only'.stem"
"onli"
```

Is it okay?

**Comment by benpickles** [comment]
Yeh, it's an expected output - and covered by the tests (taken from the original implementation: https://tartarus.org/martin/PorterStemmer/).

Input:

https://github.com/raypereda/stemmify/blob/7d30bda29122777679f2c26e4e81fb18a4d2d181/test/input.txt#L14066

Output:

https://github.com/raypereda/stemmify/blob/7d30bda29122777679f2c26e4e81fb18a4d2d181/test/output.txt#L14066

The output of the stemmed word isn't expected to be real English and is likely limited to behind the scenes usage.

> It is often taken to be a crude error that a stemming algorithm does not leave a real word after removing the stem. But the purpose of stemming is to bring variant forms of a word together, not to map a word onto its ‘paradigm’ form. 

https://tartarus.org/martin/PorterStemmer/

**Comment by Nakilon** [comment]
```
$ ruby -rstemmify -e "p 'Army'.stem"
"Army"
$ ruby -rstemmify -e "p 'army'.stem"
"armi"
$ ruby -rstemmify -e "p 'Anime'.stem"
"Anime"
$ ruby -rstemmify -e "p 'anime'.stem"
"anim"
```

Should I downcase before stemming and does it just skip if the first letter is capital?

~Also among other downcase-compare check error list I made there is a bunch of `\n`, i.e. also some bug in tokenizer.~
Nevermind, probably I just should not pass `\n` to tokenizer.

**Comment by benpickles** [comment]
It’s your responsibility to sanitise the word - which includes removing the newline and lowercasing. But it feels like the library should do it for you because (looking at the code) it uses an uppercase Y in its implementation.

```sh
$ ruby -rstemmify -e "puts 'onlY'.stem"
onlY
```
